# Generated by Django 5.0.1 on 2024-01-09 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0002_tag_posts_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="update_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Last update"
            ),
        ),
    ]
