# Generated by Django 4.2.8 on 2024-01-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_alter_post_update_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="author",),
    ]
